# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbreplicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dbreplicator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64\x62replicator.proto\"\x1a\n\tdbRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\ndbResponse\x12\x13\n\x0bresponsemsg\x18\x01 \x01(\t26\n\x0c\x64\x62Replicator\x12&\n\treplicate\x12\n.dbRequest\x1a\x0b.dbResponse\"\x00\x62\x06proto3'
)




_DBREQUEST = _descriptor.Descriptor(
  name='dbRequest',
  full_name='dbRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='dbRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=48,
)


_DBRESPONSE = _descriptor.Descriptor(
  name='dbResponse',
  full_name='dbResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responsemsg', full_name='dbResponse.responsemsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['dbRequest'] = _DBREQUEST
DESCRIPTOR.message_types_by_name['dbResponse'] = _DBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

dbRequest = _reflection.GeneratedProtocolMessageType('dbRequest', (_message.Message,), {
  'DESCRIPTOR' : _DBREQUEST,
  '__module__' : 'dbreplicator_pb2'
  # @@protoc_insertion_point(class_scope:dbRequest)
  })
_sym_db.RegisterMessage(dbRequest)

dbResponse = _reflection.GeneratedProtocolMessageType('dbResponse', (_message.Message,), {
  'DESCRIPTOR' : _DBRESPONSE,
  '__module__' : 'dbreplicator_pb2'
  # @@protoc_insertion_point(class_scope:dbResponse)
  })
_sym_db.RegisterMessage(dbResponse)



_DBREPLICATOR = _descriptor.ServiceDescriptor(
  name='dbReplicator',
  full_name='dbReplicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=85,
  serialized_end=139,
  methods=[
  _descriptor.MethodDescriptor(
    name='replicate',
    full_name='dbReplicator.replicate',
    index=0,
    containing_service=None,
    input_type=_DBREQUEST,
    output_type=_DBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBREPLICATOR)

DESCRIPTOR.services_by_name['dbReplicator'] = _DBREPLICATOR

# @@protoc_insertion_point(module_scope)
