# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dbreplicator_pb2 as dbreplicator__pb2


class dbReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.replicate = channel.unary_unary(
                '/dbReplicator/replicate',
                request_serializer=dbreplicator__pb2.dbRequest.SerializeToString,
                response_deserializer=dbreplicator__pb2.dbResponse.FromString,
                )


class dbReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dbReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.replicate,
                    request_deserializer=dbreplicator__pb2.dbRequest.FromString,
                    response_serializer=dbreplicator__pb2.dbResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbReplicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class dbReplicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbReplicator/replicate',
            dbreplicator__pb2.dbRequest.SerializeToString,
            dbreplicator__pb2.dbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
